[package]
name = "bamrescue"
version = "0.0.1"
description = "Utility to check Binary Sequence Alignment / Map (BAM) files for corruption and repair them"

authors = ["Jérémie Roquet <jroquet@arkanosis.net>"]

documentation = "https://github.com/Arkanosis/bamrescue"
homepage = "https://github.com/Arkanosis/bamrescue"
repository = "https://github.com/Arkanosis/bamrescue"

readme = "README.md"
license = "ISC"

keywords = ["bam", "integrity", "check", "repair", "bioinfo"]
categories = ["command-line-utilities"]

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
